### ISSUE TITLE
Markdown parsing is breaking on special characters when generating documentation

### ISSUE THREAD

**Issue by henvic** [electricjs/electric#152]
Example:
```
---
title: "CLI"
description: "Check out the latest releases of the WeDeploy"
layout: "updates"
updates:
 -
  version: 1.4.6
  date: May 8th, 2018
  description: Added support for using custom timezones (with environment variable TZ). Added support for deploying Git repositories. Fixing missing 'error counter'. Minor improvements.
 -
  version: 1.4.5
  date: May 4th, 2018
  description: Added release notes. Added timestamp to "we log".
 -
  version: 1.4.4
  date: Mar 30th, 2018
  description: Added 'we shell' command.
 -
  version: 1.4.2
  date: Mar 6th, 2018
  description: Renaming "we env" with "we env-var". Stop allowing dashes on service ids. Minor improvements.
---
```

It would break because of the " symbol.

@jonnilundy, can you please add the error you get when this happens?
