### ISSUE TITLE
Italics does not work in guide layouts

### ISSUE THREAD

**Issue by NolanChan** [electricjs/electric#59]
We fixed it locally by using:

```css
.docs .guide-content em {
    font-style: italic;
    font-weight: 400;
}
```
